# Generated by Django 5.2.5 on 2026-09-17 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.CharField(blank=True, help_text='Tailles vendables séparées par une virgule ; utiliser Taille unique si applicable.', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='static_image',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
