# Generated by Django 5.2.5 on 2026-09-17 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_product_sizes_product_static_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='collections',
            field=models.ManyToManyField(blank=True, help_text='Rubriques complémentaires : bébé, offres spéciales…', related_name='collection_products', to='core.category'),
        ),
    ]
