# Generated by Django 5.2.17 on 2026-09-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_product_collections'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='source_url',
            field=models.URLField(blank=True, editable=False, max_length=500, null=True, unique=True),
        ),
    ]
