# Generated by Django 5.2.17 on 2026-09-17 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_product_source_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('manage_catalog', 'Gérer le catalogue depuis la boutique')]},
        ),
        migrations.AddField(
            model_name='product',
            name='include_imported_gallery',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
