# Generated by Django 5.2.17 on 2026-09-17 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_catalog_manager_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(choices=[('femmes', 'Femme'), ('hommes', 'Homme'), ('enfants', 'Enfant')], max_length=20, unique=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homepage_selections', to='core.product')),
            ],
        ),
    ]
