# Generated by Django 5.2.17 on 2026-09-17 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_initial_homepage_selection'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='translations',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
