# Generated by Django 5.2.17 on 2026-09-23 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_product_translations'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='benefits',
            field=models.TextField(blank=True, default=None, help_text='Un bénéfice vérifié par ligne, fondé sur les caractéristiques de cet article.', null=True, verbose_name='Pourquoi le choisir ?'),
        ),
    ]
