# Generated by Django 5.2.5 on 2026-09-17 09:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(max_length=80)),
                ('items', models.JSONField()),
                ('subtotal', models.PositiveIntegerField(help_text='Montant des articles en centimes')),
                ('stripe_session_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('paid', 'Payée')], default='pending', max_length=20)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('shipping_details', models.JSONField(blank=True, default=dict)),
                ('total_paid', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
