# Generated by Django 5.2.17 on 2026-09-17 23:17

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paiement', '0002_order_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='Maison', max_length=80, verbose_name='Nom de cette adresse')),
                ('recipient', models.CharField(max_length=150, verbose_name='Destinataire')),
                ('line1', models.CharField(max_length=200, verbose_name='Adresse')),
                ('line2', models.CharField(blank=True, max_length=200, verbose_name='Complément')),
                ('postal_code', models.CharField(max_length=20, verbose_name='Code postal')),
                ('city', models.CharField(max_length=100, verbose_name='Ville')),
                ('country', models.CharField(choices=[('FR', 'France')], default='FR', max_length=2, verbose_name='Pays')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['label', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(help_text='Référence du document déjà émis. Cet enregistrement ne déclenche pas de remboursement.', max_length=100, unique=True, verbose_name='Référence de l’avoir émis')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Montant (€)')),
                ('reason', models.TextField(verbose_name='Motif')),
                ('issued_at', models.DateField(default=django.utils.timezone.localdate, verbose_name='Date d’émission')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='paiement.order')),
            ],
            options={
                'ordering': ['-issued_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Créer d’abord le code dans Stripe et y définir ses restrictions. Cette fiche ne crée pas de remise chez Stripe.', max_length=100, verbose_name='Code créé dans Stripe')),
                ('description', models.CharField(max_length=500, verbose_name='Conditions du bon')),
                ('expires_at', models.DateField(blank=True, null=True, verbose_name='Valable jusqu’au')),
                ('active', models.BooleanField(default=True, verbose_name='Actif')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
    ]
